#ifndef __BEERCALCULATOR_H__
#define __BEERCALCULATOR_H__


typedef enum BUYBEERSTATUS {
    BUYBEER_YES,
    BUYBEER_NO_TOOLDRUNK,
    BUYBEER_NO_TOOYOUNG_SYSTEMET,
    BUYBEER_NO_TOOYOUNG_KROGEN,

} BUYBEERSTATUS;

BUYBEERSTATUS canBuyBeer(int age, char location, float promille);



#endif